parameters:
- name: subscriptionEndpoint
  type: string
- name: adfName
  type: string
- name: resourceGroup
  type: string
  default: mi-$(environment)-rg
- name: adfOverrideParameters
  type: string
- name: adfAdditionalOverrideParameters
  type: string
- name: adfFolder
  type: string
  default: ./
- name: env
  type: string
  default: $(environment)
- name: agentPool
  type: string
  default: hmcts-ss-$(environment)
- name: artifactName
  type: string
  default: 'ArmTemplates'
- name: enableTriggers
  type: boolean
  default: false

jobs:
- deployment: deploy_adf
  displayName: 'Deploy to Azure Data Factory'
  pool: ${{ parameters.agentPool }}

  variables:
    packageWheelName: 'none'
  environment: ${{ parameters.env }}
  strategy:
    runOnce:
      deploy:
        steps:
        - task: CmdLine@2
          displayName: 'show filders'
          inputs:
            script: 'ls -lRt $(Pipeline.Workspace)'
        - task: CmdLine@2
          displayName: 'Prepare Az environment'
          inputs:
            script: |
              pwsh --command Install-Module -Name Az.Accounts -RequiredVersion 2.1.2 -AllowClobber -Force
              pwsh --command Install-Module -Name Az.DataFactory -RequiredVersion 1.11.4 -AllowClobber -Force
        - task: AzurePowerShell@4
          displayName: 'Azure PowerShell script: Stop ADF triggers'
          inputs:
            azureSubscription: ${{ parameters.subscriptionEndpoint }}
            ScriptPath: '$(Pipeline.Workspace)/ArmTemplates/PrePostDeploymentScript.ps1'
            ScriptArguments: '-armTemplate "$(Pipeline.Workspace)/ArmTemplates/ARMTemplateForFactory.json" -ResourceGroupName "${{ parameters.resourceGroup }}" -DataFactoryName "${{ parameters.adfName }}" -predeployment $true'
            azurePowerShellVersion: LatestVersion
        - task: Powershell@2
          inputs:
            targetType: 'inline'
            script: |
              $globalParametersExist = Test-Path -Path "$(Pipeline.Workspace)/ArmTemplates/${{ parameters.adfName }}_GlobalParameters.json"
              Write-Output "##vso[task.setvariable variable=GlobalParametersExist]$globalParametersExist"
        - task: AzurePowerShell@4
          displayName: 'Azure PowerShell script: Update global parameters'
          condition: eq(variables['GlobalParametersExist'], True)
          inputs:
            azureSubscription: ${{ parameters.subscriptionEndpoint }}
            ScriptPath: '$(Pipeline.Workspace)/ArmTemplates/GlobalParametersUpdateScript.ps1'
            ScriptArguments: '-globalParametersFilePath "$(Pipeline.Workspace)/ArmTemplates/${{ parameters.adfName }}_GlobalParameters.json" -resourceGroupName "${{ parameters.resourceGroup }}" -dataFactoryName "${{ parameters.adfName }}"'
            azurePowerShellVersion: LatestVersion
        - task: AzureResourceGroupDeployment@2
          displayName: 'Azure Deployment:Create Or Update Resource Group action on ${{ parameters.resourceGroup }}'
          inputs:
            azureSubscription: ${{ parameters.subscriptionEndpoint }}
            resourceGroupName: ${{ parameters.resourceGroup }}
            location: '$(azureLocation)'
            csmFile: '$(Pipeline.Workspace)/ArmTemplates/ARMTemplateForFactory.json'
            csmParametersFile: '$(Pipeline.Workspace)/ArmTemplates/ARMTemplateParametersForFactory.json'
            overrideParameters: -factoryName ${{ parameters.adfName }} ${{ parameters.adfOverrideParameters }} ${{ parameters.adfAdditionalOverrideParameters }}
        - task: AzurePowerShell@4
          displayName: 'Azure PowerShell script: Start ADF triggers'
          condition: eq(${{ parameters.enableTriggers }}, true)
          inputs:
            azureSubscription: ${{ parameters.subscriptionEndpoint }}
            ScriptPath: '$(Pipeline.Workspace)/ArmTemplates/PrePostDeploymentScript.ps1'
            ScriptArguments: '-armTemplate "$(Pipeline.Workspace)/ArmTemplates/ARMTemplateForFactory.json" -ResourceGroupName "${{ parameters.resourceGroup }}" -DataFactoryName "${{ parameters.adfName }}" -predeployment $false'
            azurePowerShellVersion: LatestVersion
