parameters:
- name: subscriptionEndpoint
  type: string
- name: adfName
  type: string
- name: resourceGroup
  type: string
  default: mi-$(environment)-rg
- name: adfOverrideParameters
  type: string
- name: adfFolder
  type: string
  default: ./
- name: env
  type: string
  default: $(environment)
- name: agentPool
  type: string
  default: hmcts-ss-$(environment)
- name: artifactName
  type: string
  default: 'ArmTemplates'
- name: enableTriggers
  type: boolean
  default: false

jobs:
- deployment: deploy_adf
  displayName: 'Deploy to Azure Data Factory'
  pool: ${{ parameters.agentPool }}

  variables:
    packageWheelName: 'none'
    adfOverrideParams: ${{ replace(parameters.adfOverrideParameters, ';', '\;') }} # deal with main escape chars
  environment: ${{ parameters.env }}
  strategy:
    runOnce:
      deploy:
        steps:
        - task: CmdLine@2
          displayName: 'Show Folders'
          inputs:
            script: 'ls -lRt $(Pipeline.Workspace)'
        - task: CmdLine@2
          displayName: 'Prepare Az environment'
          inputs:
            script: |
              pwsh --command Install-Module -Name Az.Accounts -RequiredVersion 2.1.2 -AllowClobber -Force
              pwsh --command Install-Module -Name Az.DataFactory -RequiredVersion 1.11.4 -AllowClobber -Force
        - task: AzurePowerShell@4
          displayName: 'Azure PowerShell script: Use preDeploymentScript and stop ADF triggers'
          inputs:
            azureSubscription: ${{ parameters.subscriptionEndpoint }}
            ScriptPath: '$(Pipeline.Workspace)/ArmTemplates/PrePostDeploymentScript.ps1'
            ScriptArguments: '-armTemplate "$(Pipeline.Workspace)/ArmTemplates/ARMTemplateForFactory.json" -ResourceGroupName "${{ parameters.resourceGroup }}" -DataFactoryName "${{ parameters.adfName }}" -predeployment $true'
            azurePowerShellVersion: LatestVersion
        - task: Powershell@2
          displayName: Check Global Parameters Existence
          inputs:
            targetType: 'inline'
            script: |
              $globalParametersExist = Test-Path -Path "$(Pipeline.Workspace)/ArmTemplates/${{ parameters.adfName }}_GlobalParameters.json"
              Write-Output "##vso[task.setvariable variable=GlobalParametersExist]$globalParametersExist"
        - task: AzurePowerShell@4
          displayName: 'Azure Powershell script: Save Existing RepoConfiguration'
          condition: eq(variables['GlobalParametersExist'], True)
          inputs:
            azureSubscription: ${{ parameters.subscriptionEndpoint }}
            scriptType: inlineScript
            inline: |
              $repoConfiguration = Get-AzDataFactoryV2 -ResourceGroupName "${{ parameters.resourceGroup }}" -Name "${{ parameters.adfName }}" | Select-Object -ExpandProperty RepoConfiguration
              Write-Output "##vso[task.setvariable variable=RepoConfigurationAccountName]$($repoConfiguration.AccountName)"
              Write-Output "##vso[task.setvariable variable=RepoConfigurationRepositoryName]$($repoConfiguration.RepositoryName)"
              Write-Output "##vso[task.setvariable variable=RepoConfigurationCollaborationBranch]$($repoConfiguration.CollaborationBranch)"
              Write-Output "##vso[task.setvariable variable=RepoConfigurationRootFolder]$($repoConfiguration.RootFolder)"
            azurePowerShellVersion: LatestVersion
        - task: AzurePowerShell@4
          displayName: 'Azure PowerShell script: Update global parameters'
          condition: eq(variables['GlobalParametersExist'], True)
          inputs:
            azureSubscription: ${{ parameters.subscriptionEndpoint }}
            ScriptPath: '$(Pipeline.Workspace)/ArmTemplates/GlobalParametersUpdateScript.ps1'
            ScriptArguments: '-globalParametersFilePath "$(Pipeline.Workspace)/ArmTemplates/${{ parameters.adfName }}_GlobalParameters.json" -resourceGroupName "${{ parameters.resourceGroup }}" -dataFactoryName "${{ parameters.adfName }}"'
            azurePowerShellVersion: LatestVersion
        - task: AzurePowerShell@4
          displayName: 'Azure Powershell script: Restore Existing HMCTS RepoConfiguration'
          condition: and(eq(variables['GlobalParametersExist'], True), eq(variables['RepoConfigurationAccountName'], 'hmcts'))
          inputs:
            azureSubscription: ${{ parameters.subscriptionEndpoint }}
            scriptType: inlineScript
            inline: |
              Get-AzDataFactoryV2 -ResourceGroupName "${{ parameters.resourceGroup }}" -Name "${{ parameters.adfName }}" | Set-AzDataFactoryV2 -HostName "https://github.com" -AccountName "$(RepoConfigurationAccountName)" -RepositoryName "$(RepoConfigurationRepositoryName)" -CollaborationBranch "$(RepoConfigurationCollaborationBranch)" -RootFolder "$(RepoConfigurationRootFolder)" -Force
            azurePowerShellVersion: LatestVersion
        - script: echo "$(adfOverrideParams)"
          displayName: "List override parameters"
        - task: AzureResourceGroupDeployment@2
          displayName: 'Azure Deployment:Create Or Update Resource Group action on ${{ parameters.resourceGroup }}'
          inputs:
            azureSubscription: ${{ parameters.subscriptionEndpoint }}
            resourceGroupName: ${{ parameters.resourceGroup }}
            location: '$(azureLocation)'
            csmFile: '$(Pipeline.Workspace)/ArmTemplates/ARMTemplateForFactory.json'
            csmParametersFile: '$(Pipeline.Workspace)/ArmTemplates/ARMTemplateParametersForFactory.json'
            overrideParameters: -factoryName ${{ parameters.adfName }} ${{ parameters.adfOverrideParameters }}
        - task: AzurePowerShell@4
          displayName: 'Azure PowerShell script: Start PostDeploymentScript'
          inputs:
            azureSubscription: ${{ parameters.subscriptionEndpoint }}
            ScriptPath: '$(Pipeline.Workspace)/ArmTemplates/PrePostDeploymentScript.ps1'
            ScriptArguments: '-armTemplate "$(Pipeline.Workspace)/ArmTemplates/ARMTemplateForFactory.json" -ResourceGroupName "${{ parameters.resourceGroup }}" -DataFactoryName "${{ parameters.adfName }}" -predeployment $false'
            azurePowerShellVersion: LatestVersion
        - task: AzurePowerShell@4
          displayName: 'Enable or Disable Pipeline Triggers'
          inputs:
            azureSubscription: ${{ parameters.subscriptionEndpoint }}
            azurePowerShellVersion: LatestVersion
            scriptType: 'inline'
            inline: |
              $triggersADF = Get-AzDataFactoryV2Trigger -DataFactoryName "${{ parameters.adfName }}" -ResourceGroupName "${{ parameters.resourceGroup }}"
              $triggersADF | ForEach-Object {
                if ("${{ parameters.enableTriggers }}" -eq "true") {
                  Start-AzDataFactoryV2Trigger -ResourceGroupName "${{ parameters.resourceGroup }}" -DataFactoryName "${{ parameters.adfName }}" -Name $_.name -Force
                }
                else {
                  Stop-AzDataFactoryV2Trigger -ResourceGroupName "${{ parameters.resourceGroup }}" -DataFactoryName "${{ parameters.adfName }}" -Name $_.name -Force
                }
              }
