parameters:
- name: subscriptionEndpoint
  type: string
- name: adfName
  type: string
  default: ''
- name: resourceGroup
  type: string
  default: mi-$(environment)-rg
- name: keyvaultName
  type: string
  default: mi-vault-$(environment)
- name: ssKeyvaultName
  type: string
  default: ss-vault-$(environment)
- name: agentPool
  type: string
  default: hmcts-ss-$(environment)
- name: databaseName
  type: string
  default: ''
- name: databaseServerName
  type: string
  default: ''
- name: azureKeyMapping
  type: object
  default: {}
- name: envMapping
  type: object
  default: {}
- name: sqlServerUserNameKey
  type: string
  default: ''
- name: sqlServerPasswordNameKey
  type: string
  default: ''
- name: dependsOn
  type: string
  default: 'deploy_adf'

jobs:
- job: run_smoke_tests
  displayName: 'Run smoke tests'
  # dependsOn: ${{ parameters.dependsOn }}
  pool: ${{ parameters.agentPool }}

  variables:
    pythonWorkingDir: './'
    pythonVersion: 3.8
  steps:
  - script: |
      set -x
      apt-get update
      echo "Python version is $pythonVersion"
      pythonVersion=3.8
      ACCEPT_EULA=Y apt-get -y install python$pythonVersion python$pythonVersion-dev  
      apt-get -y install  python$pythonVersion-venv  python$pythonVersion-distutils
      update-alternatives --install /usr/bin/python3 python3 /usr/bin/python$pythonVersion 1
      update-alternatives --set python3 /usr/bin/python  
      python3 --version
      curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
      python3 get-pip.py
    displayName: 'Install python'
  - template: ../steps/vault-secrets.yaml
    parameters: 
      azureSubscriptionEndpoint: ${{ parameters.subscriptionEndpoint }}
      keyVaultName: ${{ parameters.keyvaultName }}
      azureSecreKeys: '*'
  - task: CmdLine@2
    displayName: 'Prepare Az environment'
    inputs:
      script: 'pwsh --command Install-Module -Name Az.Accounts -RequiredVersion 2.1.2 -AllowClobber -Force'
  - task: AzureCLI@2
    inputs:
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        set -e
        python3 --version
        python3 -m venv working_dir
        source working_dir/bin/activate
        python3 -m pip install -U pip
        python3 -m pip install -r requirements.txt --no-cache-dir
        make smoke-test
        deactivate
      azureSubscription: ${{ parameters.subscriptionEndpoint }}
    env:
      SQL_SERVER_NAME: ${{ parameters.databaseServerName }}
      SQL_DATABASE_NAME: ${{ parameters.databaseName }}
      SQL_SERVER_USERNAME: '$(${{ parameters.sqlServerUserNameKey }})'
      SQL_SERVER_PASSWORD: '$(${{ parameters.sqlServerPasswordNameKey }})'
      AZ_SERVICE_PRINCIPAL_TENANT_ID: $(AZ_SERVICE_PRINCIPAL_TENANT_ID)
      AZ_SUBSCRIPTION_ID: ${{ parameters.subscriptionEndpoint }}
      AZ_RESOURCE_GROUP_NAME: ${{parameters.resourceGroup }}
      AZ_DATAFACTORY_NAME: ${{ parameters.adfName }}
      ${{ each pair in parameters.envMapping }}:
        ${{ pair.key }}: ${{ pair.value }}
      ${{ each pair in parameters.azureKeyMapping }}:
        ${{ pair.key }}: $(${{ pair.value }})
    displayName: 'Run smoke tests'

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/reports/test/*.xml'

  - task: PublishPipelineArtifact@1
    condition: succeededOrFailed()
    inputs:
      path: '$(System.DefaultWorkingDirectory)/reports/test/'
      artifact: 'smokeTest-$(environment)'
      displayName: 'Publish smoke test report'
