parameters:
- name: subscriptionEndpoint
  type: string
- name: adfName
  type: string
  default: ''
- name: resourceGroup
  type: string
  default: mi-$(environment)-rg
- name: keyvaultName
  type: string
  default: mi-vault-$(environment)
- name: ssKeyvaultName
  type: string
  default: ss-vault-$(environment)
- name: agentPool
  type: string
  default: hmcts-ss-$(environment)
- name: databaseName
  type: string
  default: ''
- name: databaseServerName
  type: string
  default: ''
- name: azureKeyMapping
  type: object
  default: {}
- name: envMapping
  type: object
  default: {}
- name: sqlServerUserNameKey
  type: string
  default: ''
- name: sqlServerPasswordNameKey
  type: string
  default: ''
- name: dependsOn
  type: string
  default: 'deploy_adf'
- name: smokeEnv
  type: string
  default: 'none'
- name: environment
  type: string

jobs:
- job: run_smoke_tests
  displayName: 'Run smoke tests'
  dependsOn: ${{ parameters.dependsOn }}
  pool: ${{ parameters.agentPool }}

  variables:
    pythonWorkingDir: './'
  steps:
  - template: ../steps/vault-secrets.yaml
    parameters: 
      azureSubscriptionEndpoint: ${{ parameters.subscriptionEndpoint }}
      keyVaultName: ${{ parameters.keyvaultName }}
      azureSecretKeys: '*'

  - script: |
      echo "ENVIRONMENT = $ENVIRONMENT"
      echo "SMOKE_ENV = $SMOKE_ENV"

      python3 -m pip install --upgrade pip
      python3 -m pip install -r requirements.txt

      python3 -m pytest src/smokeTest/test_smoke.py -v
    displayName: Run Python smoke tests
    env:
      ENVIRONMENT: ${{ parameters.environment }}
      SMOKE_ENV: ${{ parameters.smokeEnv }}

  - task: CmdLine@2
    displayName: 'Prepare Az environment'
    inputs:
      script: 'pwsh --command Install-Module -Name Az.Accounts -RequiredVersion 2.1.2 -AllowClobber -Force'
  - task: AzureCLI@2
    inputs:
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        set -e
        python3 --version
        python3 -m venv working_dir
        source working_dir/bin/activate
        python3 -m pip install -U pip
        python3 -m pip install -r requirements.txt --no-cache-dir
        make smoke-test
        deactivate
      azureSubscription: ${{ parameters.subscriptionEndpoint }}
    env:
      SQL_SERVER_NAME: ${{ parameters.databaseServerName }}
      SQL_DATABASE_NAME: ${{ parameters.databaseName }}
      SQL_SERVER_USERNAME: '$(${{ parameters.sqlServerUserNameKey }})'
      SQL_SERVER_PASSWORD: '$(${{ parameters.sqlServerPasswordNameKey }})'
      AZ_SERVICE_PRINCIPAL_TENANT_ID: $(AZ_SERVICE_PRINCIPAL_TENANT_ID)
      AZ_SUBSCRIPTION_ID: ${{ parameters.subscriptionEndpoint }}
      AZ_RESOURCE_GROUP_NAME: ${{parameters.resourceGroup }}
      AZ_DATAFACTORY_NAME: ${{ parameters.adfName }}
      ${{ each pair in parameters.envMapping }}:
        ${{ pair.key }}: ${{ pair.value }}
      ${{ each pair in parameters.azureKeyMapping }}:
        ${{ pair.key }}: $(${{ pair.value }})
    displayName: 'Run smoke tests'

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/reports/test/*.xml'

  - task: PublishPipelineArtifact@1
    condition: succeededOrFailed()
    inputs:
      path: '$(System.DefaultWorkingDirectory)/reports/test/'
      artifact: 'smokeTest-$(environment)'
      displayName: 'Publish smoke test report'
