parameters:
- name: testDirectory
  type: string
- name: azureSubscriptionName
  type: string
- name: pool
  type: string
- name: pythonVersion
  type: string
  default: 3

#Assumes that python/pip/venv have already been installed
jobs:
- job: validate_python
  displayName: Validate python
  pool: ${{ parameters.pool }}
  steps:
  - task: AzureCLI@2
    displayName: 'Validate code'
    inputs:
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        set -e
        python${{ parameters.pythonVersion}} -m venv working_dir
        source working_dir/bin/activate
        pip${{ parameters.pythonVersion}} install -U pip
        pip${{ parameters.pythonVersion}} install -r requirements.txt --no-cache-dir
        printf "\n\n\n\n\nBeginning code validation\n"
        flake8 ${{ parameters.testDirectory }} || echo "Warning - The code has styling issues that must be resolved"
        echo "Code validation complete"
        deactivate
      azureSubscription: ${{ parameters.azureSubscriptionName }}