parameters:
- name: solution
  type: string
  default: '**/*.sln'
- name: buildPlatform
  type: string
  default: 'Any CPU'
- name: buildConfiguration
  type: string
  default: 'Release'
- name: sqlDwPath
  type: string

jobs:
- job: 'validate_sql_packages'
  displayName: 'Validate sql project'
  pool:
      vmImage: 'windows-latest'
  steps:
  - task: NuGetToolInstaller@1
  - task: NuGetCommand@2
    inputs:
      restoreSolution: '${{ parameters.solution }}'
  - task: VSBuild@1
    inputs:
      solution: '${{ parameters.solution }}'
      platform: '${{ parameters.buildPlatform }}'
      configuration: '${{ parameters.buildConfiguration }}'
  - task: VSTest@2
    inputs:
      platform: '${{ parameters.buildPlatform }}'
      configuration: '${{ parameters.buildConfiguration }}'
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '${{ parameters.sqlDwPath }}/bin/${{ parameters.buildConfiguration }}/synapse.dacpac'
      ArtifactName: 'sql_dw_dacpac'
    displayName: 'Publish SQL DACPAC'  