parameters:
  rubyVersion: ''
  bundlerVersion: ''


steps:
- task: UseRubyVersion@0
  inputs:
    versionSpec: '$(rubyVersion)'

- script: |
    gem install bundler -v $(bundlerVersion)
  displayName: 'install bundler'

- script: |
    bundle install --retry=3 --jobs=4
  displayName: 'bundle install'

- script: |
    npm install --production
  displayName: 'npm install'

- script: |
    psql -h localhost -c 'create role vsts login createdb superuser;' -U postgres
  displayName: 'PG role setup'

- script: |
    bundle exec rubocop --fail-fast
  displayName: 'rubocop'

- script: |
    bundle exec rake db:create db:schema:load
  displayName: 'DB load'

- script: |
    DISPLAY=localhost:1.0 xvfb-run bundle exec cucumber --fail-fast
  displayName: 'cucumber'

- script: |
    DISPLAY=localhost:1.0 xvfb-run bundle exec rspec --fail-fast --format documentation --format RspecJunitFormatter --out test-rspec.xml
  displayName: 'rspec'

- script: |
    bundle exec rake jasmine:ci
  displayName: 'jasmine'
