name: '$(SourceBranchName)-$(Build.SourceVersion) Build-$(Build.BuildId)'

parameters:
  - name: env
    displayName: Environment to deploy
    type: string
    default: sbox
    values:
      - sbox
      - dev
      - test
      - stg
      - ithc
      - prod
  - name: secretName
    displayName: Secret name in vault
    type: string

trigger: none
pr: none

stages:
  - stage: CheckAzureVaultSecrets
    jobs:
      - job: 'CheckAzureVaultSecrets_${{ parameters.env }}'
        pool: hmcts-ss-${{ parameters.env }}
        steps:
        - template: ../templates/steps/vault-check-secret.yaml
          parameters:
            azureSubscriptionEndpoint: 'DTS-SHAREDSERVICES-${{ upper(parameters.env) }}'
            azureVault: 'mi-vault-${{ parameters.env }}'
            secretName: ${{ parameters.secretName }}
            secretValue: $(secret_value)
