name: '$(SourceBranchName)-$(Build.SourceVersion) Build-$(Build.BuildId)'

trigger:
  batch: true
  branches:
    include:
      - master

variables:
  #  group: pipeline-env-variables

  environment: 'sbox' #Use test and promoting to stg until prod is ready
  env.upper: 'SBOX'
  azure.subscription.endpoint: 'DTS-SHAREDSERVICES-$(env.upper)'

stages:
- stage: DeployAzureVaultSecrets
  jobs:
    - job: DeployAzureVaultSecrets
      pool:
        vmImage: 'Ubuntu-16.04'
      variables:
        aptDependencies: 'qtbase5-dev'
        env: ${{ parameters.env }}
      steps:
        - template: ./templates/steps/vault-upload.yaml
          parameters:
            env: $(environment)
            azureSubscriptionEndpoint: $(azure.subscription.endpoint)