name: '$(SourceBranchName)-$(Build.SourceVersion) Build-$(Build.BuildId)'

parameters:
  - name: repository
    displayName: Name of ACR Repository
    type: string
    default: mi/azure-functions

variables:
  azureSubscriptionEndpoint: 'DTS-SHAREDSERVICES-PROD'

trigger: none
pr: none

stages:
  - stage: CleanupAcr
    jobs:
      - job: 'CleanupSdsHmctsPublicAcr'
        pool:
          vmImage: 'Ubuntu-latest'
        steps:
          - task: AzureCLI@1
            displayName: "ACR Login"
            inputs:
              azureSubscription: $(azureSubscriptionEndpoint)
              scriptLocation: "inlineScript"
              inlineScript: |
                az acr login --name sdshmctspublic
          - task: AzureCLI@1
            displayName: "Cleanup ACR Repository"
            inputs:
              azureSubscription: $(azureSubscriptionEndpoint)
              scriptLocation: "inlineScript"
              inlineScript: |
                az acr repository show-manifests --name sdshmctspublic --repository "${{ parameters.repository }}"