name: '$(SourceBranchName)-$(Build.SourceVersion) Build-$(Build.BuildId)'

parameters:
  - name: env
    displayName: Environment to deploy
    type: string
    default: sbox
    values:
      - sbox
      - dev
      - test
      - stg
      - ithc
      - prod

trigger: none
pr: none

stages:
  - stage: Get Auth Key
    jobs:
      - job: 'Get Auth Key'
        pool:
          vmImage: 'Ubuntu-16.04'
        variables:
          - group: 'mi-env-${{ parameters.env }}'
        steps:
          - task: AzureCLI@2
            displayName: Azure CLI
            inputs:
              azureSubscription: DTS-SHAREDSERVICES-ITHC
              scriptType: ps
              scriptLocation: inlineScript
              inlineScript: |
                az --version
                az account show
                az datafactory integration-runtime list-auth-key --factory-name "mi-ingestion-adf-ithc" --integration-runtime-name "IR-Self-hosted" --resource-group "mi-ithc-rg"
