name: '$(SourceBranchName)-$(Build.SourceVersion) Build-$(Build.BuildId)'

parameters:
  - name: env
    displayName: Environment to deploy
    type: string
    default: sbox
    values:
      - sbox
      - dev
      - test
      - stg
      - ithc
      - prod
  - name: secretName
    displayName: Secret name in vault
    type: string

trigger: none
pr: none

stages:
  - stage: DeployAzureVaultSecrets
    jobs:
      - job: 'DeployAzureVaultSecrets_${{ parameters.env }}'
        pool: hmcts-ss-${{ parameters.env }}
        variables:
          - ${{ if eq(parameters.env, 'sbox') }}:
            clientid: f74e3f17-9785-480b-8bd4-fcac2b53c682
            subid: a8140a9e-f1b0-481f-a4de-09e2ee23f7ab
          - ${{ if eq(parameters.env, 'dev') }}:
            clientid: 5793ad47-8629-4723-82dc-78b1b49ed280
            subid: 867a878b-cb68-4de5-9741-361ac9e178b6
          - ${{ if eq(parameters.env, 'test') }}:
            clientid: b97f7ade-7db0-41b0-bac2-22effc9d79b5
            subid: 3eec5bde-7feb-4566-bfb6-805df6e10b90
          - ${{ if eq(parameters.env, 'stg') }}:
            clientid: 6ad9dea6-326e-4b34-9ccf-f7785b1ddb58
            subid: 74dacd4f-a248-45bb-a2f0-af700dc4cf68
        env: ${{ parameters.env }}
        steps:
        - template: ../templates/steps/vault-upload.yaml
          parameters:
            azureSubscriptionEndpoint: 'DTS-SHAREDSERVICES-${{ upper(parameters.env) }}'
            azureVault: 'mi-vault-${{ parameters.env }}'
            secretName: mi-house-keeping-service-managed-identity-client-id
            secretValue: ${{ variables.clientid }}
        - template: ../templates/steps/vault-upload.yaml
          parameters:
            azureSubscriptionEndpoint: 'DTS-SHAREDSERVICES-${{ upper(parameters.env) }}'
            azureVault: 'mi-vault-${{ parameters.env }}'
            secretName: azure-tenant-id
            secretValue: 531ff96d-0ae9-462a-8d2d-bec7c0b42082
        - template: ../templates/steps/vault-upload.yaml
          parameters:
            azureSubscriptionEndpoint: 'DTS-SHAREDSERVICES-${{ upper(parameters.env) }}'
            azureVault: 'mi-vault-${{ parameters.env }}'
            secretName: azure-subscription-id
            secretValue: ${{ variables.subid }}
