name: '$(SourceBranchName)-$(Build.SourceVersion) Build-$(Build.BuildId)'

parameters:
  - name: env
    displayName: Environment to deploy
    type: string
    default: sbox
    values:
      - sbox
      - dev
      - test
      - stg
      - ithc
      - prod
  - name: secretName
    displayName: Secret name in vault
    type: string
  - name: secretValue
    displayName: Secret value in group
    type: string

trigger: none
pr: none

stages:
  - stage: DeployAzureVaultSecrets
    jobs:
      - job: 'DeployAzureVaultSecrets_${{ parameters.env }}'
        pool: hmcts-ss-${{ parameters.env }}
        variables:
          - group: 'mi-env-${{ parameters.env }}'
        steps:
          - bash:
            echo "##vso[task.setvariable variable=Secret_Name;issecret=true]${{parameters.secretName}}"
          name: SetSecret
          - bash:
            echo "##vso[task.setvariable variable=Secret_Value;issecret=true]${{parameters.secretValue}}"
          name: SetSecret2
          - template: ../templates/steps/vault-upload.yaml
            parameters:
              azureSubscriptionEndpoint: 'DTS-SHAREDSERVICES-${{ upper(parameters.env) }}'
              azureVault: 'mi-vault-${{ parameters.env }}'
              keyMapping:
                - secret_name: ${{ parameters.secretName }}
                  varValue: ${{ parameters.secretValue }}