name: '$(SourceBranchName)-$(Build.SourceVersion) Build-$(Build.BuildId)'

parameters:
  - name: env
    displayName: Environment to deploy
    type: string
    default: sbox
    values:
      - sbox
      - dev
      - test
      - stg
      - ithc
      - prod
  - name: ccdro_user
    displayName: set ccd user
    type: string
    default: ccdro_user@ccd-data-store-api-postgres-db-v11-aat

trigger: none
pr: none

stages:
  - stage: DeployAzureVaultSecrets
    jobs:
      - job: 'DeployAzureVaultSecrets_${{ parameters.env }}'
        pool:
          vmImage: 'Ubuntu-16.04'
        steps:
          - template: ../templates/steps/vault-upload.yaml
            parameters:
              azureSubscriptionEndpoint: 'DTS-SHAREDSERVICES-${{ upper(parameters.env) }}'
              azureVault: 'mi-vault-${{ parameters.env }}'
              keyMapping: #mapping with secreate name and variable name
                - secret_name: ccdro_user
                  env_var_name: ${{ parameters.ccdro_user }}