name: '$(SourceBranchName)-$(Build.SourceVersion) Build-$(Build.BuildId)'

trigger:
  batch: true
  branches:
    include:
      - master

variables:
  #  group: pipeline-env-variables

  environment: 'ithc' #Use test and promoting to stg until prod is ready
  env.upper: 'ITHC'
  azure.subscription.endpoint: 'DTS-SHAREDSERVICES-$(env.upper)'
  vault: 'mi-vault-$(env)'

stages:
- stage: DeployAzureVaultSecrets
  jobs:
    - job: DeployAzureVaultSecrets
      pool:
        vmImage: 'Ubuntu-16.04'
      variables:
        env: $(environment)
      steps:
        - template: ../templates/steps/vault-upload.yaml
          parameters:
            env: $(environment)
            azureSubscriptionEndpoint: $(azure.subscription.endpoint)
            azureVault: $(vault)
