name: '$(SourceBranchName)-$(Build.SourceVersion) Build-$(Build.BuildId)'

parameters:
  - name: env
    displayName: Environment to deploy
    type: string
    default: sbox
    values:
      - sbox
      - dev
      - test
      - stg
      - ithc
      - prod

trigger: none
pr: none

stages:
  - stage: DeployAzureVaultSecrets
    jobs:
      - job: 'DeployAzureVaultSecrets_${{ parameters.env }}'
        pool:
          vmImage: 'Ubuntu-16.04'
        variables:
          - group: 'mi-env-${{ parameters.env }}'
        steps:
          - template: ../templates/steps/vault-upload.yaml
            parameters:
              azureSubscriptionEndpoint: 'DTS-SHAREDSERVICES-${{ upper(parameters.env) }}'
              azureVault: 'mi-vault-${{ parameters.env }}'
              keyMapping: #mapping with secreate name and variable name
                - secret_name: appinsights-instrumentationkey
                  env_var_name: appinsights-instrumentationkey
                - secret_name: eightbyeight-api-password
                  env_var_name: eightbyeight-api-password
                - secret_name: eightbyeight-api-user
                  env_var_name: eightbyeight-api-user
                - secret_name: gov-uk-notify-api-key
                  env_var_name: gov-uk-notify-api-key
                - secret_name: mi-datawarehouse-server
                  env_var_name: mi-datawarehouse-server
                - secret_name: mi-datawarehouse-server-admin-user
                  env_var_name: mi-datawarehouse-server-admin-user
                - secret_name: notify-api-key-cmc
                  env_var_name: notify-api-key-cmc
                - secret_name: notify-api-key-divorce
                  env_var_name: notify-api-key-divorce
                - secret_name: notify-api-key-idam
                  env_var_name: notify-api-key-idam
                - secret_name: notify-api-key-probate
                  env_var_name: notify-api-key-probate
                - secret_name: notify-api-key-sscs
                  env_var_name: notify-api-key-sscs
                - secret_name: payment-bar-db-host
                  env_var_name: payment-bar-db-host
                - secret_name: payment-bar-db-user
                  env_var_name: payment-bar-db-user
                - secret_name: payment-bar-db-password
                  env_var_name: payment-bar-db-password
                - secret_name: payment-bs-db-host
                  env_var_name: payment-bs-db-host
                - secret_name: payment-bs-db-user
                  env_var_name: payment-bs-db-user
                - secret_name: payment-bs-db-password
                  env_var_name: payment-bs-db-password
                - secret_name: payment-db-host
                  env_var_name: payment-db-host
                - secret_name: payment-db-user
                  env_var_name: payment-db-user
                - secret_name: payment-db-password
                  env_var_name: payment-db-password
                - secret_name: payment-fees-db-host
                  env_var_name: payment-fees-db-host
                - secret_name: payment-fees-db-user
                  env_var_name: payment-fees-db-user
                - secret_name: payment-fees-db-password
                  env_var_name: payment-fees-db-password
                - secret_name: mi-historical-storage-connection-string
                  env_var_name: mi-historical-storage-connection-string
                - secret_name: ccdro-user
                  env_var_name: ccdro-user
                - secret_name: ccdro-password
                  env_var_name: ccdro-password
