name: '$(SourceBranchName)-$(Build.SourceVersion) Build-$(Build.BuildId)'

parameters:
  - name: env
    displayName: Environment to deploy
    type: string
    default: sbox
    values:
      - sbox
      - dev
      - test
      - stg
      - ithc
      - prod

trigger: none
pr: none

stages:
  - stage: DeployAzureVaultSecrets
    jobs:
      - job: 'DeployAzureVaultSecrets_${{ parameters.env }}'
        pool:
          vmImage: 'Ubuntu-16.04'
        variables:
          - group: 'mi-env-${{ parameters.env }}'
        steps:
          - template: ../templates/steps/refresh-var-group-conn-strings.yaml
            parameters:
              azureSubscriptionEndpoint: 'DTS-SHAREDSERVICES-${{ upper(parameters.env) }}'
              env: '${{ parameters.env }}'
              azureVault: 'mi-vault-${{ parameters.env }}'
