name: 'Build And Set Secret String $(SourceBranchName)-$(Build.SourceVersion) Build-$(Build.BuildId)'

parameters:
  - name: env
    displayName: Environment to deploy
    type: string
    default: sbox
    values:
      - sbox
      - dev
      - test
      - stg
      - ithc
      - prod
  - name: vaultSecretName
    displayName: Secret name get value from vault.
    type: string
  - name: vaultSecretNameToSet
    displayName: Secret name to set in vault.
    type: string
  - name: vaultValueToReplace
    displayName: Value to replace.
    type: string
    default: "v11"
  - name: vaultValueReplace
    displayName: Value to replace with.
    type: string
    default: "v15"

trigger: none
pr: none

stages:
  - stage: ReplaceSecretString
    jobs:
      - job: 'ReplaceSecretString_${{ parameters.env }}'
        pool: hmcts-ss-${{ parameters.env }}
        steps:
          - task: AzureCLI@2
            displayName: "Replace value in vault"
            inputs:
              azureSubscription: 'DTS-SHAREDSERVICES-${{ upper(parameters.env) }}'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                vaultName="mi-vault-${{ parameters.env }}"
                currentValue=$(az keyvault secret show --vault-name $vaultName --name ${{ parameters.vaultSecretName }} --query 'value' -o tsv)
                newValue=${currentValue//"${{ parameters.vaultValueToReplace }}"/"${{ parameters.vaultValueReplace }}"}
                trimmedNewValue=$(echo $newValue | xargs)

                az keyvault secret set --name ${{ parameters.vaultSecretNameToSet }} --vault-name $vaultName --value "$trimmedNewValue" --output none
