
name: Java CI

on:
  push:
    branches:
      - master
      - refs/tags/*
    tags:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Build
        run: ./gradlew check
      - name: Release
        if: github.ref == 'refs/heads/master'
        env:
          BINTRAY_USER: jenkins-reform-hmcts
          BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
        run: ./gradlew bintrayUpload
